# Generated by Django 5.2.1 on 2025-05-21 12:44

import core.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher number means a higher priority in listing."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["-order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", core.fields.AutoDateTimeField(default=django.utils.timezone.now)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Selecting this option will publish this item"
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", core.fields.RichTextField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher number means a higher priority in listing."
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faqs",
                        to="faqs.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["-order", "question"],
            },
        ),
    ]
