# Generated by Django 5.2.1 on 2025-05-21 12:44

import core.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", core.fields.AutoDateTimeField(default=django.utils.timezone.now)),
                ("text", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "new_tab",
                    models.BooleanField(
                        default=False, help_text="Open this link in a new tab/window."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Set to prioritise the order of this link, higher numbers are shown first.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Check this if you would like to display this link in the footer.",
                    ),
                ),
            ],
            options={
                "ordering": ["-order", "text", "-created_at"],
            },
        ),
    ]
