# Generated by Django 5.2.1 on 2025-05-21 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyStatisticContainer",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("introduction", models.TextField(blank=True)),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stat_value", models.CharField(max_length=50)),
                ("strapline", models.CharField(max_length=255)),
                (
                    "plugin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plugin_statistics",
                        to="key_stat.keystatisticcontainer",
                    ),
                ),
            ],
        ),
    ]
