# Generated by Django 5.2.1 on 2025-05-21 14:15

import core.fields
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingEnquiry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", core.fields.AutoDateTimeField(default=django.utils.timezone.now)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Mr", "Mr"),
                            ("Mrs", "Mrs"),
                            ("Miss", "Miss"),
                            ("Ms", "Ms"),
                            ("Dr", "Dr"),
                            ("Prof", "Prof"),
                            ("Sir", "Sir"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "primary_vehicle_reg",
                    models.CharField(
                        help_text="This would typically be the storage vehicle", max_length=8
                    ),
                ),
                (
                    "secondary_vehicle_reg",
                    models.CharField(
                        help_text="This would typically be the towing vehicle", max_length=8
                    ),
                ),
                ("address_line_one", models.CharField(max_length=255)),
                ("address_line_two", models.CharField(blank=True, max_length=255)),
                ("postcode", models.CharField(max_length=8)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
                ),
            ],
            options={
                "verbose_name_plural": "Booking Enquiries",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
