# Generated by Django 4.2.13 on 2024-07-08 08:35

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("hero_carousel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="file",
        ),
        migrations.AlterField(
            model_name="image",
            name="internal_link",
            field=cms.models.fields.PageField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_internal_links",
                to="cms.page",
            ),
        ),
    ]
