version: '3.7'
services:

  cache:
    image: redis:latest

  web:
    &appbase
    build:
      context: .
      target: "base"
    command: src/manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.local
    environment:
      - ALLOWED_HOSTS=0.0.0.0
      - DJANGO_SETTINGS_MODULE=core.settings
      - SECRET_KEY=development-secret
      - PRIMARY_HOST=localhost
      - DEPLOY_ENV=local
      - DEBUG=True
      - DATABASE_URL=sqlite://app/local.sqlite
      - REDIS_URL=redis://cache
    
  # frontend:
  #   depends_on: 
  #     - web
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "5173:5173"

  # test:
  #   <<: *appbase
  #   ports: []
  #   command: pytest src/
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=core.settings
  #     - DATABASE_URL=sqlite://app/test.sqlite
  #     - DEPLOY_ENV=test
  #     - SECRET_KEY=test-secret

  # mail:
  #   image: mailhog/mailhog
  #   # platform: linux/amd64
  #   ports:
  #     - "127.0.0.1:8025:8025"

  # queue:
  #   <<: *appbase
  #   command: src/manage.py qcluster
  #   ports: []
