# Generated by Django 4.2.1 on 2023-06-07 13:11

import cms.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import giant_news.models.article
import mixins.fields
import swapper


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("cms", "0022_auto_20180620_1551"),
        ("giant_news", "0001_initial"),
        swapper.dependency("giant_news", "Article"),
    ]

    run_before = [
        ('giant_news', '0002_relatedarticlecardplugin_relatedarticleplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", mixins.fields.AutoDateTimeField(default=django.utils.timezone.now)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Selecting this option will publish this item"
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("intro", models.CharField(max_length=255)),
                ("meta_title", models.CharField(blank=True, max_length=160)),
                ("meta_description", models.CharField(blank=True, max_length=255)),
                ("plugin_text", models.TextField(blank=True, editable=False)),
                (
                    "author",
                    models.ForeignKey(
                        default=giant_news.models.article._default_author,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="%(app_label)s_%(class)ss",
                        to="giant_news.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        to="giant_news.category",
                    ),
                ),
                (
                    "content",
                    cms.models.fields.PlaceholderField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)ss",
                        slotname="content",
                        to="cms.placeholder",
                    ),
                ),
                (
                    "photo",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_images",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="%(app_label)s_%(class)s_tags",
                        to="giant_news.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": ["-publish_at"],
                "abstract": False,
            },
        ),
    ]
