# Generated by Django 4.2.2 on 2023-07-04 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_article_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
    ]
