# Generated by Django 4.2.2 on 2023-07-04 12:39

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("news", "0003_remove_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=taggit_autosuggest.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
