# Generated by Django 4.2.16 on 2024-10-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("cms", "0022_auto_20180620_1551"),
        ("case_studies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudyCardsPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, help_text="Limit case studies based on tags.", to="taggit.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="CaseStudyCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "case_study",
                    models.ForeignKey(
                        limit_choices_to={"is_published": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_study_cards",
                        to="case_studies.casestudy",
                        verbose_name="Case Study",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_case_studies",
                        to="case_study_cards.casestudycardsplugin",
                    ),
                ),
            ],
        ),
    ]
