# Generated by Django 4.2.13 on 2024-07-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialShareImageExtension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "extended_object",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="cms.page"
                    ),
                ),
                (
                    "public_extension",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_extension",
                        to="page_extension.socialshareimageextension",
                    ),
                ),
                (
                    "social_share_image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        help_text="Recommended size: 1500 x 1000 pixels.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IndexExtension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "do_not_index",
                    models.BooleanField(
                        default=False,
                        help_text="If ticked, this page will not be indexed by search engines.",
                    ),
                ),
                (
                    "extended_object",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="cms.page"
                    ),
                ),
                (
                    "public_extension",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_extension",
                        to="page_extension.indexextension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
