# Generated by Django 5.2.1 on 2025-05-21 12:44

import django.core.validators
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        help_text="\n            Enter the full URL of the youtube video page.\n            To start the video at a specific time add '&t=xx' to the end of the url (using\n            seconds). You can also add extra paramaters using an ampersand, for example\n            '&t=75&autoplay=1'.\n        ",
                        null=True,
                        validators=[
                            django.core.validators.URLValidator(
                                message="Please enter the full URL of the Youtube video page",
                                regex="www.youtube.com",
                                schemes=["https"],
                            )
                        ],
                    ),
                ),
                (
                    "alternate_url",
                    models.URLField(
                        blank=True,
                        help_text="This will be used if no Youtube URL is provided",
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("alt_text", models.CharField(blank=True, max_length=128)),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin", models.Model),
        ),
    ]
