# Generated by Django 4.2.13 on 2024-07-08 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="\n            Enter the full URL of the youtube video page.\n            To start the video at a specific time add '&t=xx' to the end of the url (using\n            seconds). You can also add extra paramaters using an ampersand, for example\n            '&t=75&autoplay=1'.\n        ",
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        message="Please enter the full URL of the Youtube video page",
                        regex="www.youtube.com",
                        schemes=["https"],
                    )
                ],
            ),
        ),
    ]
