# Generated by Django 4.2.16 on 2024-10-30 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("giant_news", "0007_relatedarticleplugin_title"),
        ("taggit", "0005_auto_20220424_2025"),
        ("cms", "0022_auto_20180620_1551"),
        migrations.swappable_dependency(settings.GIANT_NEWS_ARTICLE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCardsPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("article_count", models.IntegerField(default=3)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit articles based on a category.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="giant_news.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit articles based on tags.",
                        limit_choices_to={"articles__isnull": False},
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="ArticleCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_published": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_cards",
                        to=settings.GIANT_NEWS_ARTICLE_MODEL,
                        verbose_name="Article",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_cards",
                        to="article_cards.articlecardsplugin",
                    ),
                ),
            ],
        ),
    ]
