# Generated by Django 4.2.16 on 2024-10-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("events", "0001_initial"),
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCardsPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Limit events based on tags.",
                        limit_choices_to={"events__isnull": False},
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="EventCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        limit_choices_to={"is_published": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_cards",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_events",
                        to="event_cards.eventcardsplugin",
                    ),
                ),
            ],
        ),
    ]
